CREATE TABLE `AUTH` (
  `USN` INT PRIMARY KEY NOT NULL,
  `PASSWORD` INT NOT NULL
);

CREATE TABLE `TRANSACTIONS` (
  `R_ID` INT NOT NULL,
  `T_ID` INT PRIMARY KEY NOT NULL,
  `AMOUNT` INT NOT NULL,
  `MODE` INT NOT NULL,
  `STATUS` INT NOT NULL
);

CREATE TABLE `STUDENTS` (
  `USN` INT PRIMARY KEY NOT NULL,
  `DEPT` INT NOT NULL,
  `SEM` INT NOT NULL,
  `SECTION` INT NOT NULL,
  `PHONE` INT NOT NULL,
  `EVENTS` INT NOT NULL
);

CREATE TABLE `COORDINATORS` (
  `USN` INT PRIMARY KEY NOT NULL,
  `ROLE` INT NOT NULL,
  `EVENT` INT NOT NULL
);

CREATE TABLE `REGISTRATION` (
  `R_ID` INT PRIMARY KEY NOT NULL,
  `E_ID` INT NOT NULL,
  `USN` INT NOT NULL,
  `TIMESTAMP` INT NOT NULL,
  `DESK_ID` INT NOT NULL,
  `DESK_USN` INT NOT NULL,
  `DESKLOCATION` INT NOT NULL,
  `T_ID` INT NOT NULL
);

CREATE TABLE `EVENTS` (
  `E_ID` INT PRIMARY KEY NOT NULL,
  `NAME` INT NOT NULL,
  `DATE` INT NOT NULL,
  `TIME` INT NOT NULL,
  `DURATION` INT NOT NULL,
  `VENUE` INT NOT NULL,
  `PRICE` INT NOT NULL,
  `COORDINATORS` INT NOT NULL,
  `RULES` INT NOT NULL,
  `CATEGORY` INT NOT NULL,
  `TEAM_COUNT` INT NOT NULL,
  `COLOR` INT NOT NULL
);

ALTER TABLE `COORDINATORS` ADD FOREIGN KEY (`USN`) REFERENCES `STUDENTS` (`USN`);

ALTER TABLE `COORDINATORS` ADD FOREIGN KEY (`USN`) REFERENCES `AUTH` (`USN`);

ALTER TABLE `REGISTRATION` ADD FOREIGN KEY (`T_ID`) REFERENCES `TRANSACTIONS` (`T_ID`);

ALTER TABLE `REGISTRATION` ADD FOREIGN KEY (`E_ID`) REFERENCES `EVENTS` (`E_ID`);

ALTER TABLE `REGISTRATION` ADD FOREIGN KEY (`USN`) REFERENCES `STUDENTS` (`USN`);

ALTER TABLE `TRANSACTIONS` ADD FOREIGN KEY (`R_ID`) REFERENCES `REGISTRATION` (`R_ID`);

ALTER TABLE `COORDINATORS` ADD FOREIGN KEY (`USN`) REFERENCES `EVENTS` (`COORDINATORS`);

ALTER TABLE `EVENTS` ADD FOREIGN KEY (`E_ID`) REFERENCES `COORDINATORS` (`EVENT`);

ALTER TABLE `EVENTS` ADD FOREIGN KEY (`E_ID`) REFERENCES `STUDENTS` (`EVENTS`);

ALTER TABLE `COORDINATORS` ADD FOREIGN KEY (`USN`) REFERENCES `REGISTRATION` (`DESK_USN`);
